version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - sqlc generate
builds:
  - env:
      - CGO_ENABLED=1
    ldflags:
      - -X github.com/sgaunet/ekspodlogs/cmd.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    # dir: src
    id: ekspodlogs


archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
